train: C:\Users\Heet\Downloads\Microplastics.v1i.yolov8\train
val: C:\Users\Heet\Downloads\Microplastics.v1i.yolov8\valid
test: C:\Users\Heet\Downloads\Microplastics.v1i.yolov8\test

nc: 3
names: ['bead', 'fiber', 'fragment']

roboflow:
  workspace: demo-r4lnt
  project: microplastics-m71tn
  version: 1
  license: CC BY 4.0
  url: https://universe.roboflow.com/demo-r4lnt/microplastics-m71tn/dataset/1